// Le etichette dell'interfaccia nelle lingue che offriamo. E' un file JS e non un JSON
// perche' un JSON andrebbe letto con una fetch, con il caricamento da aspettare: qui si
// importa e le etichette sono gia' a disposizione.
// I testi delle opere non stanno qui: quelli li scrive il backend, che li traduce nella
// lingua scelta e li salva insieme agli altri.

// tag: quello che vogliono speechSynthesis (per pronunciare) e SpeechRecognition (per capire)
export const LINGUE = [
  { codice: 'it', nome: 'Italiano', tag: 'it-IT' },
  { codice: 'en', nome: 'English', tag: 'en-GB' },
  { codice: 'fr', nome: 'Français', tag: 'fr-FR' },
  { codice: 'es', nome: 'Español', tag: 'es-ES' },
  { codice: 'de', nome: 'Deutsch', tag: 'de-DE' },
];

export const TRADUZIONI = {
  it: {
    lingua: 'Lingua', livello: 'Livello', durata: 'Durata',
    livelli: { infantile: 'Bambino', elementare: 'Studente', medio: 'Generale', specialistico: 'Esperto' },
    durate: { '3s': '3 sec', '15s': '15 sec', '1min': '1 min', '4min': '4 min' },
    nessunTesto: 'Nessun testo disponibile.',
    testoNonDisponibile: 'Questo testo non è disponibile.',
    nessunItem: 'Nessun item presente in questo percorso.',
    tappa: 'Tappa',
    infoTitolo: 'Informazioni utili',
    infoVuoto: 'Nessuna informazione disponibile.',
    chiudi: 'Chiudi',
    ariaChiudiVisita: 'Chiudi visita', ariaInfo: 'Informazioni utili',
    ariaMappa: 'Mappa', ariaTornaLettura: 'Torna alla lettura',
    ariaPrecedente: 'Item precedente', ariaSuccessivo: 'Item successivo',
    ariaAscolta: 'Ascolta', ariaPausa: 'Pausa', ariaAudioNo: 'Audio non disponibile',
    ariaPreparando: 'Sto preparando il testo',
    ariaMicrofono: 'Comando vocale', ariaFermaMicrofono: 'Ferma ascolto',
    ariaQr: "Inquadra il QR di un'opera", ariaChiudiQr: 'Chiudi la fotocamera',
    ascoltando: 'Sto ascoltando...', unMomento: 'Un momento...',
    hoCapito: 'Ho capito', nonHoCapito: 'Non ho capito', nonHoSentito: 'Non ho sentito, riprova',
    fuoriVisita: (titolo) => `"${titolo}" non fa parte di questa visita.`,
    codiceIgnoto: 'Questo codice non corrisponde a nessuna opera.',
    fotocameraKo: 'Non riesco ad aprire la fotocamera.',
    comandi: {
      prossimo: 'Prossimo', precedente: 'Precedente', pausa: 'Pausa', riprendi: 'Riprendi',
      ripeti: 'Ripeti', leggi: 'Leggi', piuDettagli: 'Più dettagli', menoDettagli: 'Meno dettagli',
      piuSemplice: 'Più semplice', piuAvanzato: 'Più avanzato', esci: 'Esci',
      comeCiArrivo: 'Come ci arrivo', autore: 'Autore', stile: 'Stile',
      uscita: 'Uscita', toilette: 'Toilette', bar: 'Bar', shop: 'Shop', ostacoli: 'Ostacoli e accessibilità',
    },
    frase: { autore: (a) => `L'autore è ${a}`, stile: (s) => `Lo stile è ${s}` },
  },

  en: {
    lingua: 'Language', livello: 'Level', durata: 'Length',
    livelli: { infantile: 'Child', elementare: 'Student', medio: 'General', specialistico: 'Expert' },
    durate: { '3s': '3 sec', '15s': '15 sec', '1min': '1 min', '4min': '4 min' },
    nessunTesto: 'No text available.',
    testoNonDisponibile: 'This text is not available.',
    nessunItem: 'This tour has no items.',
    tappa: 'Stop',
    infoTitolo: 'Useful information',
    infoVuoto: 'No information available.',
    chiudi: 'Close',
    ariaChiudiVisita: 'Close tour', ariaInfo: 'Useful information',
    ariaMappa: 'Map', ariaTornaLettura: 'Back to the text',
    ariaPrecedente: 'Previous item', ariaSuccessivo: 'Next item',
    ariaAscolta: 'Listen', ariaPausa: 'Pause', ariaAudioNo: 'Audio not available',
    ariaPreparando: 'Preparing the text',
    ariaMicrofono: 'Voice command', ariaFermaMicrofono: 'Stop listening',
    ariaQr: 'Scan the QR code of an artwork', ariaChiudiQr: 'Close the camera',
    ascoltando: 'Listening...', unMomento: 'One moment...',
    hoCapito: 'Understood', nonHoCapito: "I didn't get", nonHoSentito: "I didn't hear you, try again",
    fuoriVisita: (titolo) => `"${titolo}" is not part of this tour.`,
    codiceIgnoto: 'This code does not match any artwork.',
    fotocameraKo: 'I cannot open the camera.',
    comandi: {
      prossimo: 'Next', precedente: 'Previous', pausa: 'Pause', riprendi: 'Resume',
      ripeti: 'Repeat', leggi: 'Read', piuDettagli: 'More detail', menoDettagli: 'Less detail',
      piuSemplice: 'Simpler', piuAvanzato: 'More advanced', esci: 'Exit',
      comeCiArrivo: 'How do I get there', autore: 'Artist', stile: 'Style',
      uscita: 'Exit door', toilette: 'Toilets', bar: 'Café', shop: 'Shop', ostacoli: 'Accessibility',
    },
    frase: { autore: (a) => `The artist is ${a}`, stile: (s) => `The style is ${s}` },
  },

  fr: {
    lingua: 'Langue', livello: 'Niveau', durata: 'Durée',
    livelli: { infantile: 'Enfant', elementare: 'Élève', medio: 'Général', specialistico: 'Expert' },
    durate: { '3s': '3 sec', '15s': '15 sec', '1min': '1 min', '4min': '4 min' },
    nessunTesto: 'Aucun texte disponible.',
    testoNonDisponibile: "Ce texte n'est pas disponible.",
    nessunItem: 'Ce parcours ne contient aucun contenu.',
    tappa: 'Étape',
    infoTitolo: 'Informations utiles',
    infoVuoto: 'Aucune information disponible.',
    chiudi: 'Fermer',
    ariaChiudiVisita: 'Fermer la visite', ariaInfo: 'Informations utiles',
    ariaMappa: 'Plan', ariaTornaLettura: 'Retour au texte',
    ariaPrecedente: 'Contenu précédent', ariaSuccessivo: 'Contenu suivant',
    ariaAscolta: 'Écouter', ariaPausa: 'Pause', ariaAudioNo: 'Audio non disponible',
    ariaPreparando: 'Je prépare le texte',
    ariaMicrofono: 'Commande vocale', ariaFermaMicrofono: "Arrêter l'écoute",
    ariaQr: "Scannez le QR code d'une œuvre", ariaChiudiQr: 'Fermer la caméra',
    ascoltando: "J'écoute...", unMomento: 'Un instant...',
    hoCapito: 'Compris', nonHoCapito: "Je n'ai pas compris", nonHoSentito: "Je n'ai rien entendu, réessayez",
    fuoriVisita: (titolo) => `"${titolo}" ne fait pas partie de cette visite.`,
    codiceIgnoto: "Ce code ne correspond à aucune œuvre.",
    fotocameraKo: "Je n'arrive pas à ouvrir la caméra.",
    comandi: {
      prossimo: 'Suivant', precedente: 'Précédent', pausa: 'Pause', riprendi: 'Reprendre',
      ripeti: 'Répéter', leggi: 'Lire', piuDettagli: 'Plus de détails', menoDettagli: 'Moins de détails',
      piuSemplice: 'Plus simple', piuAvanzato: 'Plus avancé', esci: 'Quitter',
      comeCiArrivo: "Comment y aller", autore: 'Auteur', stile: 'Style',
      uscita: 'Sortie', toilette: 'Toilettes', bar: 'Café', shop: 'Boutique', ostacoli: 'Accessibilité',
    },
    frase: { autore: (a) => `L'auteur est ${a}`, stile: (s) => `Le style est ${s}` },
  },

  es: {
    lingua: 'Idioma', livello: 'Nivel', durata: 'Duración',
    livelli: { infantile: 'Niño', elementare: 'Estudiante', medio: 'General', specialistico: 'Experto' },
    durate: { '3s': '3 seg', '15s': '15 seg', '1min': '1 min', '4min': '4 min' },
    nessunTesto: 'No hay texto disponible.',
    testoNonDisponibile: 'Este texto no está disponible.',
    nessunItem: 'Este recorrido no tiene contenidos.',
    tappa: 'Parada',
    infoTitolo: 'Información útil',
    infoVuoto: 'No hay información disponible.',
    chiudi: 'Cerrar',
    ariaChiudiVisita: 'Cerrar la visita', ariaInfo: 'Información útil',
    ariaMappa: 'Plano', ariaTornaLettura: 'Volver al texto',
    ariaPrecedente: 'Contenido anterior', ariaSuccessivo: 'Contenido siguiente',
    ariaAscolta: 'Escuchar', ariaPausa: 'Pausa', ariaAudioNo: 'Audio no disponible',
    ariaPreparando: 'Estoy preparando el texto',
    ariaMicrofono: 'Comando de voz', ariaFermaMicrofono: 'Detener la escucha',
    ariaQr: 'Escanea el código QR de una obra', ariaChiudiQr: 'Cerrar la cámara',
    ascoltando: 'Estoy escuchando...', unMomento: 'Un momento...',
    hoCapito: 'Entendido', nonHoCapito: 'No he entendido', nonHoSentito: 'No te he oído, inténtalo otra vez',
    fuoriVisita: (titolo) => `"${titolo}" no forma parte de esta visita.`,
    codiceIgnoto: 'Este código no corresponde a ninguna obra.',
    fotocameraKo: 'No consigo abrir la cámara.',
    comandi: {
      prossimo: 'Siguiente', precedente: 'Anterior', pausa: 'Pausa', riprendi: 'Continuar',
      ripeti: 'Repetir', leggi: 'Leer', piuDettagli: 'Más detalles', menoDettagli: 'Menos detalles',
      piuSemplice: 'Más sencillo', piuAvanzato: 'Más avanzado', esci: 'Salir',
      comeCiArrivo: 'Cómo llego', autore: 'Autor', stile: 'Estilo',
      uscita: 'Salida', toilette: 'Aseos', bar: 'Cafetería', shop: 'Tienda', ostacoli: 'Accesibilidad',
    },
    frase: { autore: (a) => `El autor es ${a}`, stile: (s) => `El estilo es ${s}` },
  },

  de: {
    lingua: 'Sprache', livello: 'Niveau', durata: 'Dauer',
    livelli: { infantile: 'Kind', elementare: 'Schüler', medio: 'Allgemein', specialistico: 'Experte' },
    durate: { '3s': '3 Sek', '15s': '15 Sek', '1min': '1 Min', '4min': '4 Min' },
    nessunTesto: 'Kein Text verfügbar.',
    testoNonDisponibile: 'Dieser Text ist nicht verfügbar.',
    nessunItem: 'Dieser Rundgang enthält keine Inhalte.',
    tappa: 'Station',
    infoTitolo: 'Nützliche Hinweise',
    infoVuoto: 'Keine Hinweise verfügbar.',
    chiudi: 'Schließen',
    ariaChiudiVisita: 'Rundgang schließen', ariaInfo: 'Nützliche Hinweise',
    ariaMappa: 'Plan', ariaTornaLettura: 'Zurück zum Text',
    ariaPrecedente: 'Vorheriger Inhalt', ariaSuccessivo: 'Nächster Inhalt',
    ariaAscolta: 'Anhören', ariaPausa: 'Pause', ariaAudioNo: 'Audio nicht verfügbar',
    ariaPreparando: 'Der Text wird vorbereitet',
    ariaMicrofono: 'Sprachbefehl', ariaFermaMicrofono: 'Zuhören beenden',
    ariaQr: 'QR-Code eines Werks scannen', ariaChiudiQr: 'Kamera schließen',
    ascoltando: 'Ich höre zu...', unMomento: 'Einen Moment...',
    hoCapito: 'Verstanden', nonHoCapito: 'Ich habe nicht verstanden', nonHoSentito: 'Ich habe nichts gehört, bitte noch einmal',
    fuoriVisita: (titolo) => `"${titolo}" gehört nicht zu diesem Rundgang.`,
    codiceIgnoto: 'Dieser Code gehört zu keinem Werk.',
    fotocameraKo: 'Die Kamera lässt sich nicht öffnen.',
    comandi: {
      prossimo: 'Weiter', precedente: 'Zurück', pausa: 'Pause', riprendi: 'Fortsetzen',
      ripeti: 'Wiederholen', leggi: 'Vorlesen', piuDettagli: 'Mehr Details', menoDettagli: 'Weniger Details',
      piuSemplice: 'Einfacher', piuAvanzato: 'Anspruchsvoller', esci: 'Beenden',
      comeCiArrivo: 'Wie komme ich dorthin', autore: 'Künstler', stile: 'Stil',
      uscita: 'Ausgang', toilette: 'Toiletten', bar: 'Café', shop: 'Shop', ostacoli: 'Barrierefreiheit',
    },
    frase: { autore: (a) => `Der Künstler ist ${a}`, stile: (s) => `Der Stil ist ${s}` },
  },
};
